---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: idx-scale
  namespace: splunk-cluster-prod
spec:
  scaleTargetRef:
    apiVersion: enterprise.splunk.com/v2
    kind: IndexerCluster
    name: idx-dev
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sh-scale
  namespace: splunk-cluster-prod
spec:
  scaleTargetRef:
    apiVersion: enterprise.splunk.com/v2
    kind: SearchHeadCluster
    name: sh-dev
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75
