---
apiVersion: enterprise.splunk.com/v2
kind: Standalone
metadata:
  name: standalone-dev
  namespace: splunk-standalone-prod
  finalizers:
    - enterprise.splunk.com/delete-pvc
  labels:
    app: SplunkStandalone
    type: Splunk
spec:
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.1"
    limits:
      memory: "12Gi"
      cpu: "8"
  etcVolumeStorageConfig:
    storageCapacity: 10Gi
    storageClassName: longhorn
  varVolumeStorageConfig:
    storageCapacity: 100Gi
    storageClassName: longhorn
  volumes:
    - name: defaults
      configMap:
        name: splunk-standalone-defaults
    - name: licenses
      configMap:
        name: splunk-licenses
  licenseUrl: /mnt/licenses/enterprise.lic
  defaultsUrl: /mnt/defaults/default.yml
