---
kubernetes:
  children:
    master:
      hosts:
        k8s-0:
          ansible_host: 10.10.1.50
        k8s-1:
          ansible_host: 10.10.1.51
        k8s-2:
          ansible_host: 10.10.1.52
    worker:
      hosts:
        k8s-3:
          ansible_host: 10.10.1.53
        k8s-4:
          ansible_host: 10.10.1.54
