---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # renovate: registryUrl=https://github.com/splunk/splunk-operator/releases/download/
  - https://github.com/splunk/splunk-operator/releases/download/1.0.3/splunk-operator-crds.yaml
