---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-config-v1
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-retain
