---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://prymalinstynct.github.io/helm-charts
      chart: uptime-kuma
      version: 1.0.3
      sourceRef:
        kind: HelmRepository
        name: prymalinstynct-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: longhorn
      namespace: storage
  values:
    image:
      repository: louislam/uptime-kuma
      pullPolicy: IfNotPresent
      tag: 1.11.1
    podSecurityContext:
      fsGroup: 0
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "list-status"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "uptime.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "uptime.${SECRET_DOMAIN}"
            secretName: uptime-kuma-tls
    persistence:
      config:
        enabled: true
        existingClaim: uptime-kuma-config-v1
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
