---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: focalboard
  namespace: productivity
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: focalboard
      version: 4.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: longhorn
      namespace: storage
  values:
    image:
      repository: mattermost/focalboard
      pullPolicy: IfNotPresent
      tag: 0.11.0
    podSecurityContext:
      fsGroup: 0
    enableServiceLinks: false
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "notebook-outline"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "focalboard.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "focalboard.${SECRET_DOMAIN}"
            secretName: focalboard-tls
    persistence:
      data:
        enabled: true
        existingClaim: focalboard-data-v1
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
    # See the Administrator's Guide for config reference: https://www.focalboard.com/guide/admin/
    config: |
      {
        "serverRoot": "http://localhost:8000",
        "port": 8000,
        "dbtype": "sqlite3",
        "dbconfig": "/data/focalboard.db",
        "dbtableprefix": "",
        "postgres_dbconfig": "dbname=focalboard sslmode=disable",
        "test_dbconfig": "file::memory:?cache=shared",
        "useSSL": false,
        "webpath": "/data/webapp/pack",
        "filesdriver": "local",
        "filespath": "/data/files",
        "telemetry": true,
        "prometheus_address": ":9092",
        "webhook_update": [],
        "session_expire_time": 2592000,
        "session_refresh_time": 18000,
        "localOnly": false,
        "enableLocalMode": true,
        "localModeSocketLocation": "/var/tmp/focalboard_local.socket",
        "authMode": "native",
        "logging_cfg_file": "",
        "audit_cfg_file": "",
        "enablepublicsharedboards": true
      }
