# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:pgpXNKWbFPQ7VDI=,iv:YmRgIegnuH+52w/M+pXvHl44RyFqWPvZE92eVhgUoUU=,tag:YBK43NG4uzsYeskLX3k6Ng==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:y7O1HZBFpPA486Vvmik91gbrrQg=,iv:8s9BHBqamhdnBQjacKm4iB4MmBQyluEWVmNrB7wA+f4=,tag:iKkXWEooZozPNmFS4jDiIA==,type:str]
    SECRET_QB_PASSWORD: ENC[AES256_GCM,data:YQk0fOGwiMRaZg==,iv:N59i7PpvATTaZb0ftmllCxqqpoFbYHxccdv1/M1ELNU=,tag:gRE1OYISVEh+grzlCXiztg==,type:str]
    SECRET_QB_USERNAME: ENC[AES256_GCM,data:d4J8tdDQnBYFQg==,iv:7gGo4lVO7X2h/G+7Sp8UbBcqeVt5lbVsSMAyg8AIvOA=,tag:iT1I1nPM+0bnfkHmqikNRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y30f7kpheak5cv3m9tetx73xpeswztagxqw8k8xz9m7005xgzqvqg43q0h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMjREVGpnR1NPUGJYNmpU
            Q3F3SzhqRnNZU1MvZEtaN1JId0ZTWGFGeG1BCmYySjB4Sjl2WVBiUzVUM20yUnpV
            b3d1ZkpGdlJJT2xHUDhDdUhDNDhjOUUKLS0tIDhVOU5ick1XMTl0OWZyNWRVNlpY
            UFBkcUtzbk5aQXJwK0hNaEpyTWtjajQKnunvIk/8amQcNcrmfhrLn4IHUDZkeJb/
            guPQKkkv5dvofwcHFriX3jQo6Ch7oV1TR6mwKPsc1a7RnwUwnoKv7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-03T14:14:03Z"
    mac: ENC[AES256_GCM,data:Sr1FKfikq/s4HiG/mH/YpirwjzsnMeRtPzxOE5yOE3Yjj3hDBeZqLWBb5RvI0GdJaPuGTZBqqQy6QHHtECNN7u29lgVjcP1TDD6yMyCfswmWRvc6rEqCLrXKGTVJwwPJ1O9rCoFqJfGYZm1NrP2pX29XKU9GOOZ+PxuwNL3/yVM=,iv:Q2Dvr1FkMRmYoI/mqn1uROD7KzxSWFd4+QZfvzLscuY=,tag:IkWNh0VTGUcVrylPB0YzYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
