---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default
  - kube-system
  - media
  - minecraft
  - monitoring
  - networking
  - productivity
  # - splunk-cluster
  # - splunk-standalone
  - storage
  - system-upgrade
