---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: busybox
  namespace: minecraft
spec:
  interval: 4m
  chart:
    spec:
      # renovate: registryUrl=https://prymalinstynct.github.io/helm-charts
      chart: busybox-chart
      version: 0.1.17
      sourceRef:
        kind: HelmRepository
        name: prymalinstynct-charts
        namespace: flux-system
      interval: 4m
  dependsOn:
    - name: nfs-provisioner
      namespace: storage
