---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cron-job.yaml
  - secret.sops.yaml
namespace: networking
configMapGenerator:
  - name: cloudflare-ddns-info
    files:
      - cloudflare-ddns-info.sh
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
