# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-info
    namespace: networking
type: Opaque
# CLOUDFLARE_EMAIL: The email used to log into https://dash.cloudflare.com
# CLOUDFLARE_APIKEY: Top right corner, "My profile" > "Global API Key"
# CLOUDFLARE_ZONEID: Can be found in the "Overview" tab of your domain
# CLOUDFLARE_RECORD_NAME: The name of your A record
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:iIjsSIkFl/p57gc7RsNbmJd+XZ0=,iv:Fp+mrUOhMZ1FA2XJFw9AOXla25vuhYLI5ZYP5XNghf0=,tag:sXO/DNroRv7ry6/S4Oy+sQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:+Jnhfx7dG3/QG4//d4IZyoQSlUlzdn568ukwg2S6WDauRBnCkw==,iv:sWdG2ODi2KFv7keuwJCSB+O0GXvEBDOYy2urdNdzaRo=,tag:akydc7bKJX65ASOmuCE75Q==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:9C94Tauhaqo4N6SxviFaXg==,iv:ebT4GdWKTpaSislaD523iuKQc636r1HE3/mQe1BPN8A=,tag:JYDU1vak6NvRrqydsTZcGg==,type:str]
    CLOUDFLARE_ZONEID: ENC[AES256_GCM,data:mBFsn0eAFZ/bNhq4K5HnpFvZhIQwxJ4zYgoSM3uM8Ow=,iv:PGZGwfgqLjAVdUfgtq/NXDcipmSnPlKe3yHaNa51ces=,tag:tAJ17UhWmzQnlSL4SwILag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y30f7kpheak5cv3m9tetx73xpeswztagxqw8k8xz9m7005xgzqvqg43q0h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NG85ck1jMFJTOHd1Smov
            VUNTQnVabmhncTd4MFpTeWhwanNtWHE2aFFJCnFxazdyM3lxdnpvakFMUHZURTQ3
            OGY0enBLZTFyc0JzMU92dmYwK1hYalEKLS0tIHBCbjdTaFFFUTRtY2lqZmgycmRv
            My9VbzRsUi9iL040ZGlGclZnNXJoTUkKxLMfdBvxdnLj09voCP6qUrX2G6Hg5HMf
            MxGGK8bGugiqnEl0DPIVsASzOQtb2wjYPgb/dn1k/23GmDGTCLHO+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-03T13:18:22Z"
    mac: ENC[AES256_GCM,data:dwyBqhT745rzxI/4gqX7tFvAiDTxfS20uNTlS+QRRaGUhNj/LYQk5yDCdg/6mw6DyYEhQStVss0YC6+wjxgUgLAiQXIkVrsxpl6MvdKm29TbPPGXtyXW7iZc/HhYOyqizPZcaHilHHmHhIJRmZTvuFSBfsa9TyXQjjDYr8p9ejc=,iv:HQGDeZu0rW1upmrAQJDc4i6F0tG9gL0Sl3PuZ+cqPR4=,tag:A0mja1R9nCYF26JJXnYmag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
