# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:Xgrl4oeydhV27DQmt6Ti6Bwd1zrFnwEVud3jg/OjWLlA4KyJEg==,iv:nIO26LdpIuJB7GRRs1qAS6gSGBaCbHPS0Lm0sQnV9ks=,tag:r1BrsITPA4p6LTytI+v9vg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y30f7kpheak5cv3m9tetx73xpeswztagxqw8k8xz9m7005xgzqvqg43q0h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTlhCNDZEa0YrdHVNYkNE
            TVhaY05oWXVZaStRTHNCNDRxems3UU5uNjBJCmRXQTNQZ3FHRURNa3dXaVp3RXdL
            Ykh2cysvam9MZFFmSzdaSlg5dUw5MEEKLS0tIFBpT01xSGVqYlFmWW1nT1VJREl0
            VW9jQjJqNllzL1JCYmlVd2dQWTBKN2cKivfviS3LqgBmQYT/4lovsvSGP8LD8xG5
            zaY0iH2jG6jnG/yIt6eVAKUdmuf2H3YAZbvGKEm23Xk7NAS6YGXQEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-03T12:45:02Z"
    mac: ENC[AES256_GCM,data:O7eedL3mFBK/zsCNQAdzBMLzQQ55NHK1fiqJQKiUbTjqRM+neHj3FCAxrRbTfP1UsUEOMrCU/B1ppL+6SQv7F9BuGy4kmFmG1T+uRekOo8c9OopZiMY2N/+JxblwKGxr8bEGojciSt353HOJ0m+pwU6q1VnP9xHGOdst8vqHOT8=,iv:+YMzGV/xJwo8U7qNgqEe39Yk08bbVmy8EGBcJRzAnsY=,tag:5Xk1W3HHjpcRYPQQyUrnZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
