---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: default
spec:
  interval: 4m
  chart:
    spec:
      # renovate: registryUrl=https://hajimari.io
      chart: hajimari
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: hajimari-charts
        namespace: flux-system
      interval: 4m
  values:
    image:
      repository: ghcr.io/toboshii/hajimari
      tag: v0.2.0
    hajimari:
      defaultEnable: false
      namespaceSelector:
        matchNames:
          - default
          - media
          - networking
          - storage
      name: "PrymalNet - Production"
      # customApps:
      #   - name: Some External Cluster Service
      #     url: http://192.168.1.100:5000
      #     icon: test-tube
      groups:
        - name: Useful
          links:
            - name: Github
              url: "https://github.com/PrymalInstynct"
            - name: Cloudflare
              url: "https://cloudflare.com"
            - name: A Cloud Guru
              url: "https://acloudguru.com/#sign-in"
        - name: Google
          links:
            - name: Gmail
              url: "https://mail.google.com"
            - name: Drive
              url: "https://drive.google.com"
            - name: Docs
              url: "https://docs.google.com"
            - name: Sheets
              url: "https://drive.google.com"
            - name: Domains
              url: "https://domains.google.com"
        - name: Media
          links:
            - name: Spotify
              url: "http://open.spotify.com"
            - name: YouTube
              url: "https://youtube.com/feed/subscriptions"
        - name: Tech News
          links:
            - name: The Hacker News
              url: "https://thehackernews.com"
            - name: The Verge
              url: "https://theverge.com/"
            - name: MIT Technology Review
              url: "https://www.technologyreview.com/"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "weather-sunset"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-basic-auth@kubernetescrd"
        hosts:
          - host: "hajimari.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "hajimari.${SECRET_DOMAIN}"
            secretName: "hajimari-tls"
    persistence:
      data:
        enabled: true
        existingClaim: hajimari-config
    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-settings"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
